### ISSUE TITLE
Error installing with VS 2022 17.8.6

### ISSUE THREAD

**Issue by trinare** [QuadSpinner/Highlighter#14]
When trying to install the extension for Visual Studio Professional 2022 17.8.6, I get the following error:

"Install Failed. The install of 'Highlighter' was not successful for all the selected products."

Here is the error from the log:

6/26/2024 10:44:18 AM - The extension with ID 'QuadSpinner.Highlighter.4b62' is not installed to Visual Studio Professional 2022.
6/26/2024 10:44:18 AM - Found installed product - Global Location
6/26/2024 10:44:18 AM - Extension Details...
6/26/2024 10:44:18 AM - 	Identifier         : QuadSpinner.Highlighter.4b62
6/26/2024 10:44:18 AM - 	Name               : Highlighter
6/26/2024 10:44:18 AM - 	Author             : Dax Pandhi
6/26/2024 10:44:18 AM - 	Version            : 1.0.1.10
6/26/2024 10:44:18 AM - 	Description        : An arbitrary highlighter that lets you pick individual class, parameter, or other element names to highlight across your projects. It makes it easier to find and identify objects inside your project. You can also use it for comment annotations, dividers, and more.
6/26/2024 10:44:18 AM - 	Locale             : en-US
6/26/2024 10:44:18 AM - 	MoreInfoURL        : https://github.com/QuadSpinner/Highlighter
6/26/2024 10:44:18 AM - 	InstalledByMSI     : False
6/26/2024 10:44:18 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
6/26/2024 10:44:18 AM - 	SignatureState     : Unsigned
6/26/2024 10:44:18 AM - 	Supported Products : 
6/26/2024 10:44:18 AM - 		Microsoft.VisualStudio.Community
6/26/2024 10:44:18 AM - 			Version : [17.0,18.0]
6/26/2024 10:44:18 AM - 			ProductArchitecture : amd64
6/26/2024 10:44:18 AM - 	References         : 
6/26/2024 10:44:18 AM - 	Prerequisites      : 
6/26/2024 10:44:18 AM - 		-------------------------------------------------------
6/26/2024 10:44:18 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/26/2024 10:44:18 AM - 		Name         : Visual Studio core editor
6/26/2024 10:44:18 AM - 		Version      : [17.0,)
6/26/2024 10:44:18 AM - Signature Details...
6/26/2024 10:44:18 AM - 	Extension is not signed.
6/26/2024 10:44:20 AM - Microsoft.VisualStudio.ExtensionManager.CorruptInstanceException: VSIX Installer has encountered a problem. To troubleshoot, follow the steps here: https://aka.ms/pc5ifb ---> Microsoft.VisualStudio.Setup.Dependencies.DependencyGraphConstructionException: The dependent package of 'Microsoft.VC.14.38.17.8.Props.ARM,version=14.38.33138' cannot be found: Microsoft.VC.14.38.17.8.Props,version=14.38.33138.
   at Microsoft.VisualStudio.Setup.Engine.GetProductDependencyGraph(Product product, Boolean overwrite)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.IntializePackages()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisitesInternal(IInstallableExtension extension, ICollection`1 installedPackages, ICollection`1 installablePackages, ICollection`1 unresolvedReferences)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisites(IInstallableExtension extension, IEnumerable`1& installedPackages, IEnumerable`1& installablePackages, IEnumerable`1& unresolvedReferences)
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   --- End of inner exception stack trace ---
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by daxpandhi** [comment]
I'll check it out and make an update asap. Thanks!

**Comment by trinare** [comment]
After trying a to install a different extension, I got the same error. I also get an error about Microsoft.VC.14.38.17.8 when I try to modify my Visual Studio install. I think this is a problem on my machine and not with your extension. Sorry about that! Thanks for the quick reply!

**Comment by daxpandhi** [comment]
Good to know! Thank you for the update. I'm closing this bug for now, but if it pops back up please let me know.
